### ISSUE TITLE
Admin - General settings: Missing tagline as per Design Brief 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#100]
![image](https://cloud.githubusercontent.com/assets/13363508/9845207/e1abbe30-5afb-11e5-9363-4d5d3cb84353.png)

**Comment by maehtitan** [comment]
<b>Please apply the tagline specified in the design brief</b>

**Comment by ravititan** [comment]
fixed. page title need to be edited
