### ISSUE TITLE
Product Single View & Promos - Enquire Now button: Post title value is empty, which doesn't shows up the Post Title and Post URL in the autoresponder

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#102]
<b>These are the screenshot for the empty value: </b>
![image](https://cloud.githubusercontent.com/assets/13363508/10009325/6af7f318-610d-11e5-95e0-e83bbe3ec51f.png)

<h5> After clicking the enquire button above it looks like this the Address URL: http://airforce.stage.titanweb.com.au/contact-us/?posttitle=

<h5>And this is what I received in the autoresponder
![image](https://cloud.githubusercontent.com/assets/13363508/10009355/01581c5c-610e-11e5-962c-766f26d8f571.png)

<h4> It should be looks like this in the correct autoresponder, sample below:
![image](https://cloud.githubusercontent.com/assets/13363508/10009366/314168a6-610e-11e5-8848-3aa15e590cde.png)

Please check standard implementation here: https://knowledgebase.titanweb.com.au/implementation-practices/gravity-forms/quote-enquiry-form-on-posts

**Comment by maehtitan** [comment]
Post title has value already but it doesn't reflect in the autoresponder after filling up the contact us form the Post Title and the Post URL
![image](https://cloud.githubusercontent.com/assets/13363508/10036274/ee8db256-61d7-11e5-994e-5ffb6e530e35.png)


<h5> Form received
![image](https://cloud.githubusercontent.com/assets/13363508/10036282/129296d0-61d8-11e5-9a01-2c710afe4e24.png)

**Comment by maehtitan** [comment]
<h5>
![image](https://cloud.githubusercontent.com/assets/13363508/10041453/e95fa958-6216-11e5-87e2-be7046e33c90.png)

Standard below:
![image](https://cloud.githubusercontent.com/assets/13363508/10041467/079c6f32-6217-11e5-8036-669a72b10ed9.png)

Please apply fix also on the screenshot of the product page single view below
![image](https://cloud.githubusercontent.com/assets/13363508/10041577/9c4117be-6217-11e5-9590-b85829bd4d02.png)

**Comment by ravititan** [comment]
{embed_post:post_title} is showing Contact Us as post title...
