### ISSUE TITLE
Blog: When Clicking the Read More button, Read Less button is left aligned in a blog post with featured image 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#104]
![image](https://cloud.githubusercontent.com/assets/13363508/10009594/1ff22c26-6112-11e5-9f5d-c9ed0dcad517.png)

**Comment by maehtitan** [comment]
As what the design shows the blog post content shouldn't be wrapped with the image it should be aligned in vertically

![image](https://cloud.githubusercontent.com/assets/13363508/10035947/9f446708-61d2-11e5-8a1e-835d192cb3f3.png)

**Comment by ravititan** [comment]
i wrapped content and readmore button to image... which will fill the whitespace below image to look better... !

**Comment by maehtitan** [comment]
It's just for your personal preference but we need to follow what the actual design shows
