### ISSUE TITLE
Product - Post Title Value: Why is it that when passing the post title there are additional numbers and special character in the URL

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#114]
![image](https://cloud.githubusercontent.com/assets/13363508/10066110/123d2f98-62c2-11e5-810d-ca419d2e0e5b.png)

**Comment by ravititan** [comment]
when sending through URL, some strings (ie. 'post titles' in our case) may get terminated in the middle when special characters are there between, so need to encode them...

**Comment by maehtitan** [comment]
Okay.Thanks
