### ISSUE TITLE
Admin - Pages - Home: unable to edit "Prefooter - Get in Touch" coz text field heading ACF and WYSIWYG for description ACF are missing

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#116]
![image](https://cloud.githubusercontent.com/assets/13363508/10091988/309abc46-6374-11e5-85f7-7552500fb14a.png)

**Comment by ravititan** [comment]
but footer is in all pages.... not only in homepage ??

**Comment by maehtitan** [comment]
It clearly stated on the project scope "ACF group on home page" meaning add the ACF to the homepage, which means editing the Get in touch prefooter can be done in the homepage and changes will be made to all pages, coz there is only 1 common footer design no other design for the inner footer.

Please apply changes to inner pages footer please
