### ISSUE TITLE
W3C - Homepage: 3 Errors

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#132]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fairforce.stage.titanweb.com.au%2F

![image](https://cloud.githubusercontent.com/assets/13363508/10182974/27c4635a-675d-11e5-84dc-222744ff3276.png)

**Comment by ravititan** [comment]
as we have to get dynamic values for styles... we need to put style tag in php file..

**Comment by maehtitan** [comment]
@ravititan Why is it that the same functionality with the leadins hover effect and no issue found in the leadins style here: http://cmeboilermaking.stage.titanweb.com.au/, also accdg to the dev here it can be fixed.
