### ISSUE TITLE
Products-Listing page: Font-color for the breadcrumbs separators should be #848484. Currently used #00adef.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Airforce-Air-Conditioning#17]
1. Applicable for all single pages.

![lorem ipsum archives_breadcrm](https://cloud.githubusercontent.com/assets/13309730/9440229/05b364e4-4a8b-11e5-85d8-abbec7408c67.png)

![products_singlepa](https://cloud.githubusercontent.com/assets/13309730/9440234/105c776e-4a8b-11e5-8bb4-fbaa6909cd33.png)

**Comment by ravititan** [comment]
is it #848484 or #797979 ??
