### ISSUE TITLE
Products-Listing page: Breadcrumbs should be placed above the header not below the header

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Airforce-Air-Conditioning#18]
1. Applicable to all single pages.

![products_breadcrmb](https://cloud.githubusercontent.com/assets/13309730/9440352/1e3da1ea-4a8c-11e5-9d50-569f8f5f763b.png)

**Comment by ravititan** [comment]
according to kb below heading

**Comment by mahender-sowedane** [comment]
Kindly stop working on this project as this is currently not assigned to you.
