### ISSUE TITLE
Manuals page: 'Download' button breaks to the next line on devices.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Airforce-Air-Conditioning#23]
Devices: I touch, Samsung E7 and I pad mini(P).

![manual_downld](https://cloud.githubusercontent.com/assets/13309730/9458752/4c343684-4b10-11e5-8773-6a15537e4e81.jpg)

**Comment by ravititan** [comment]
it is intentionally BREAKS to next line in tabs and mobiles
