### ISSUE TITLE
Homepage: Image is cut 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#48]
![image](https://cloud.githubusercontent.com/assets/13363508/9710843/ed10c526-5570-11e5-97ab-b0393b25f57f.png)

**Comment by ravititan** [comment]
which device? 
not able to reproduce...

**Comment by maehtitan** [comment]
Screenshot above obviously shows in desktop view specifically Firefox browsers but not only in this browsers shows, it only occurs on all browsers 

<b>Opera</b>
![image](https://cloud.githubusercontent.com/assets/13363508/9840618/a60df3ae-5ac7-11e5-843c-83841f45d6c1.png)

<b>IE</b>
![image](https://cloud.githubusercontent.com/assets/13363508/9840652/fd6bac22-5ac7-11e5-90b4-40bfb6ab55e9.png)

<b>Increasing the padding-bottom will move the image down </b>
![image](https://cloud.githubusercontent.com/assets/13363508/9840691/a2e7705a-5ac8-11e5-8982-de5dd1587a2a.png)
