### ISSUE TITLE
Homepage: Image is stretched and pixelated compared to the design provided which is not.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#49]
![image](https://cloud.githubusercontent.com/assets/13363508/9710904/9662a680-5571-11e5-8cd0-8439da2aba25.png)

**Comment by ravititan** [comment]
which device? 
not able to reproduce...

**Comment by maehtitan** [comment]
@ravititan This is in desktop view, in all browsers, Image on the right above obviously expanded that's why it is a bit blurry compared to the .PSd

**Comment by ravititan** [comment]
the new image you uploaded, is not stretched...

**Comment by ravititan** [comment]
![image](https://cloud.githubusercontent.com/assets/13450891/9956224/bd163a2a-5e14-11e5-9b9a-2e5e836ac2ef.png)

**Comment by maehtitan** [comment]
<b>Yes, it is not stretched coz it was a big file image but you make it pixelated by the add the %, please see below SS:</b>

![image](https://cloud.githubusercontent.com/assets/13363508/9984329/ff415b84-6047-11e5-9b23-69fe23b7620d.png)


<b>After removing the 82% of the image is back to its original shape</b>
![image](https://cloud.githubusercontent.com/assets/13363508/9984351/6ad122b2-6048-11e5-91fb-afcab31959d0.png)
