### ISSUE TITLE
FAQ : Arrow up not working.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Airforce-Air-Conditioning#5]
![faq_01](https://cloud.githubusercontent.com/assets/13309730/9435953/a36a976a-4a69-11e5-9680-8355dab35e17.png)

**Comment by ravititan** [comment]
all my projects have same functionality

**Comment by mahender-sowedane** [comment]
Kabir has fixed this type of bug in one of his project, please take his help and fix this.

**Comment by mahender-sowedane** [comment]
After having discussion with TL, closed the issue.
