### ISSUE TITLE
General: Found a console log which run the height in the browser console

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#54]
![image](https://cloud.githubusercontent.com/assets/13363508/9727308/1bd0fd1c-5630-11e5-955d-38448e0827eb.png)

**Comment by ravititan** [comment]
![image](https://cloud.githubusercontent.com/assets/13450891/9789574/971f5134-57ee-11e5-9196-04e2a269fcb6.png)

**Comment by maehtitan** [comment]
Console log still not removed

![image](https://cloud.githubusercontent.com/assets/13363508/9842634/28976894-5ae3-11e5-9edf-2944327c6c5a.png)
