### ISSUE TITLE
General - Console - IE9, IE10, IE11: Found 8 errors in console log which it effects the footer font that doesn't reflected just like how to rest of the browsers displays

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#55]
![image](https://cloud.githubusercontent.com/assets/13363508/9727326/524ed8e6-5630-11e5-99f7-1344e2dfc9b8.png)
![image](https://cloud.githubusercontent.com/assets/13363508/9730227/b2e060e6-5647-11e5-8067-3d6454cfdd68.png)

**Comment by maehtitan** [comment]
<h5> Issues was back and gave the same error just like before which changes the fonts in IE browsers (9,10,11)

**Comment by maehtitan** [comment]
Font attributes are visibly fixed but the the console are still there

**Comment by ravititan** [comment]
those errors are coming from font formats used for other browsers,,, as IE cannot decode them it will show errors... it is ignorable...
