### ISSUE TITLE
Blog: Limit shorten description by 4 lines as per design provided

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#63]
![image](https://cloud.githubusercontent.com/assets/13363508/9730504/9381e092-5649-11e5-909e-54f3bcad7c56.png)

**Comment by ravititan** [comment]
already limited to four lines...

**Comment by maehtitan** [comment]
It doesn't limits to 4 especially to the top post Test Blog and also in the 2nd page, please see screenshot below
![image](https://cloud.githubusercontent.com/assets/13363508/9840752/a4f2db40-5ac9-11e5-89f4-f3cb869af3bf.png)

**Comment by maehtitan** [comment]
Text is cut and it doesn't limit to 4
![image](https://cloud.githubusercontent.com/assets/13363508/9984886/58edea70-6053-11e5-8e77-7f3198cd2175.png)
