### ISSUE TITLE
Home page: "Read More" button is missing in IE9.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Airforce-Air-Conditioning#7]
![ie9](https://cloud.githubusercontent.com/assets/13309730/9438360/c76b31c2-4a7a-11e5-8c92-c1b2ed923d59.png)

**Comment by ravititan** [comment]
it is not missing.. enough content was not posted

**Comment by mahender-sowedane** [comment]
why it's displaying other browsers, please explain why it's invalid.. or fix it

**Comment by ravititan** [comment]
![1](https://cloud.githubusercontent.com/assets/13450891/9561702/6aef03b8-4e6e-11e5-90ba-c3df34cd5900.jpg)

**Comment by mahender-sowedane** [comment]
When i'm testing i found that issue, have a look above screenshot, but now it's fixed.
