### ISSUE TITLE
General - Pages - Content Area: Alphabetical list turns to number

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#72]
![image](https://cloud.githubusercontent.com/assets/13363508/9752645/5f504b14-56e5-11e5-96a0-ad473ad4ddf6.png)

**Comment by ravititan** [comment]
where is alphabetical list? anyway fixed...

**Comment by maehtitan** [comment]
This is our dummy contents template in word... I paste the letters in lowercase but it turns out uppercase

![image](https://cloud.githubusercontent.com/assets/13363508/9843102/af564976-5ae9-11e5-9a7f-b7f86fe6220b.png)

**Comment by ravititan** [comment]
fixed
note: dont paste content from word... create ordered and unordered lists from our wysiwyg editor

**Comment by ravititan** [comment]
![image](https://cloud.githubusercontent.com/assets/13450891/9953100/3fc091a6-5dfb-11e5-92a5-e59a2a0419ff.png)

**Comment by maehtitan** [comment]
@ravi-josyula It should work either way.
