### ISSUE TITLE
Home page: Banner section is distorting on IE9.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Airforce-Air-Conditioning#8]
![home_page_ie9](https://cloud.githubusercontent.com/assets/13309730/9438431/4329a618-4a7b-11e5-959a-5822c97acde2.png)

**Comment by mahender-sowedane** [comment]
Please explain why it's invalid.. and have a look above screenshot properly and fix it..

**Comment by ravititan** [comment]
![1](https://cloud.githubusercontent.com/assets/13450891/9561697/37838f76-4e6e-11e5-8aa4-ac377f15c6f4.jpg)

**Comment by mahender-sowedane** [comment]
When i'm testing i found that issue, have a look above screenshot, but now it's fixed.
