### ISSUE TITLE
Product - Categories and Sub-category Category description not properly styled

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#81]
![image](https://cloud.githubusercontent.com/assets/13363508/9754532/b056033e-56fc-11e5-8684-5d3375096e4f.png)

**Comment by ravititan** [comment]
description field only accepts a simple paragraph...

**Comment by maehtitan** [comment]
https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/categories-and-sub-categories

**Comment by ravititan** [comment]
without proper formatting, styles will not be applied to word pasted content. 

styles will be applied if description field has wysiwyg editor...

**Comment by maehtitan** [comment]
It has to be consisted with the other pages.

**Comment by ravititan** [comment]
need to edit core plugin files...

**Comment by ravititan** [comment]
our TL said it will be marked as enhancement
