### ISSUE TITLE
W3C - Product Sub - Category: 3 Errors

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#84]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fairforce.stage.titanweb.com.au%2Fproduct-category%2Ftest-category%2F

**Comment by ravititan** [comment]
![image](https://cloud.githubusercontent.com/assets/13450891/9762237/df6ae3d8-571f-11e5-8f3d-a92784dec19b.png)
