### ISSUE TITLE
W3C - Product Single View: 6 Errors

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#85]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fairforce.stage.titanweb.com.au%2Fproducts%2Fsub-category%2Ftest-product-text-and-image%2F

**Comment by ravititan** [comment]
![image](https://cloud.githubusercontent.com/assets/13450891/9758905/1fbcf912-5707-11e5-87f9-3f71a1162a14.png)
