### ISSUE TITLE
W3C - Project Single View - Promos Single view: 1 Error found

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#86]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fairforce.stage.titanweb.com.au%2Fpromos_manager%2Ftest-projects-text-and-image%2F

**Comment by ravititan** [comment]
![image](https://cloud.githubusercontent.com/assets/13450891/9762136/fd73a0d2-571e-11e5-8c8b-6fc080a3d331.png)
