### ISSUE TITLE
Admin - Homepage: You can use the Page title as Main Heading instead of creating new ACF for the main heading

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#98]
![image](https://cloud.githubusercontent.com/assets/13363508/9844975/38bd4cb8-5afa-11e5-8cf6-9436ec564aa7.png)

**Comment by ravititan** [comment]
If we change page title.... title in the <title> tag will also change... that is the reason im using separate field... 

![image](https://cloud.githubusercontent.com/assets/13450891/9897290/277a593a-5c64-11e5-949d-803126c82c6e.png)

**Comment by ravititan** [comment]
![image](https://cloud.githubusercontent.com/assets/13450891/9897344/9fc85b1c-5c64-11e5-80af-01a3ce8144f4.png)

**Comment by maehtitan** [comment]
<b>Yes, obviously it needs to change since that is not the final meta title of the page and if the clients wants to add another text for the page that's the time they need to go to the General Settings> and fill up the Tagline which is disabled at the moment (coz I added a Test title and it doesn't add to the meta title) and most implemented sites here are currently using the page title as the main heading to minimize the ACF counts</b>
