### ISSUE TITLE
Admin - Leadins: Should be using the featured image as an image ACF

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Airforce-Air-Conditioning#99]
![image](https://cloud.githubusercontent.com/assets/13363508/9845107/400981e8-5afb-11e5-8cc3-352a63268fbc.png)

**Comment by ravititan** [comment]
featured image cannot be used as we have to give hover image option also...

**Comment by maehtitan** [comment]
I will mark this one as wont fix since this is the Project Scope fault. Please update the project scope
